In [27]:
import torch

In [28]:
min_type= float('-inf')

In [29]:
seq_len=tgt_len=mask_len=5
causal_mask = torch.full((seq_len, tgt_len), fill_value=min_type)

In [30]:
causal_mask

tensor([[-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf]])

In [31]:
causal_mask = torch.triu(causal_mask, diagonal=1)

In [32]:
causal_mask

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [33]:
token_type_ids=torch.zeros(seq_len)
token_type_ids[-2:]=1

In [34]:
causal_mask[ :, :mask_len] = causal_mask[:, :mask_len].masked_fill(token_type_ids[None, :] == 0, 0)

In [35]:
causal_mask

tensor([[0., 0., 0., -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [36]:
softmax_probs = torch.softmax(causal_mask, dim=-1)

In [37]:
softmax_probs

tensor([[0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000]])